### ISSUE TITLE
Re-align default map view

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/mandates-map#163]
![image](https://github.com/ParkingReformNetwork/mandates-map/assets/86996158/bb4acbb9-bdc4-403e-b316-0a1743fcad8c)

The javascript migration map is shifted down due to header being a flex box. 

One fix: adjust latitude and longitude of default map view in setUpSite.js

**Comment by Eric-Arellano** [comment]
> One fix: adjust latitude and longitude of default map view in setUpSite.js

A better fix is to do this with CSS. For example, add a new `div class="page"` that wraps the banner div and the map div. Use either CSS grid or CSS flexbox (with vertical alignment rather than the default of horizontal) on `.page`. We want the browser to correctly position elements automatically.

Keep in mind with adjusting latitude/longitude that the solution doesn't scare well to different screen sizes. The adjustment will need to be bigger or smaller depending on the screen size.
